#!/usr/bin/env python3
"""Derive spamoor's child wallets from a sim config and premine them.

    ./spamoor-premine.py sim-<N>nodes-<label>.yaml --inject
    ./spamoor-premine.py sim-<N>nodes-<label>.yaml --check <data>/metadata/genesis.json

spamoor funds its child wallets with on-chain transactions and waits for them
to confirm before the scenario starts.  On an EL running --maxpeers 0 that
funding transaction only confirms when that one node proposes, which at 100
nodes never happened -- the private blob arm sat in "funding child wallets...
(0/2)" for a whole run.

prepareWallet (spamoor f3b5828 walletpool.go:894) only builds a funding
request when the child's balance is below --refill-balance, so a child that is
already rich at genesis is skipped and the scenario starts on its first tick.
The child key is deterministic:

    childKey = sha256(rootPrivKey || bigEndianUint64(idx) || seed)

which is what spamoor-children computes -- build spamoor-children.go and put
the binary in $SIM_BIN_DIR, or name it outright with $SPAMOOR_CHILDREN.  The
seed has to be pinned with
--seed in the instance's extra_args: spamoor's default is
"<scenario>-<random int>", so without it the addresses change every run.

--inject rewrites the block between the BEGIN/END marker comments in the sim
config.  --check re-derives from the same config and asserts every root and
every child is in a generated EL genesis alloc with a balance.
"""

import argparse
import os
import re
import subprocess
import sys

try:
    import yaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml")

HERE = os.path.dirname(os.path.abspath(__file__))
BIN_DIR = os.environ.get("SIM_BIN_DIR", os.path.join(HERE, "bin"))
CHILDREN = os.environ.get("SPAMOOR_CHILDREN", os.path.join(BIN_DIR, "spamoor-children"))
BALANCE = "1000000ETH"
BEGIN = "    # BEGIN spamoor child wallets"
END = "    # END spamoor child wallets"


def instances(cfg):
    """Every spamoor client in the config, with its seed and wallet count."""
    out = []
    for name, client in cfg["ethereum"]["clients"].items():
        if client.get("type") != "spamoor":
            continue
        seed = re.search(r"--seed\s+(\S+)", client.get("extra_args", "") or "")
        if not seed:
            sys.exit(f"{name}: no --seed in extra_args; child addresses would "
                     f"be random every run")
        count = client.get("max_wallets")
        if not count:
            sys.exit(f"{name}: max_wallets must be set explicitly, otherwise "
                     f"the scenario picks the count and we cannot premine it")
        # An unquoted 0x... key is valid YAML for an integer, so pyyaml hands
        # it back as one.  Re-pad to 32 bytes; a key with a leading zero byte
        # would otherwise come back short.
        privkey = client["private_key"]
        if isinstance(privkey, int):
            privkey = "0x%064x" % privkey
        out.append({
            "name": name,
            "privkey": str(privkey),
            "seed": seed.group(1),
            "count": int(count),
        })
    return sorted(out, key=lambda i: i["name"])


def derive(inst):
    """Child addresses for one instance, straight out of spamoor's own scheme."""
    res = subprocess.run(
        [CHILDREN, inst["privkey"], inst["seed"], str(inst["count"])],
        capture_output=True, text=True, check=True)
    return [line.split()[1] for line in res.stdout.splitlines() if line.strip()]


def root_address(privkey):
    res = subprocess.run([CHILDREN, privkey, "", "0"],
                         capture_output=True, text=True, check=True)
    return res.stdout.split()[1]


def block(insts):
    lines = [BEGIN, "    # (generated by spamoor-premine.py -- do not hand-edit)",
             "    premine:"]
    for inst in insts:
        lines.append(f"      # {inst['name']}: seed {inst['seed']}, "
                     f"{inst['count']} child wallets")
        for addr in derive(inst):
            lines.append(f'      "{addr}": "{BALANCE}"')
    lines.append(END)
    return "\n".join(lines)


def inject(path, insts):
    text = open(path).read()
    start = text.index(BEGIN)
    stop = text.index(END) + len(END)
    # Build first, write second: a derivation failure must not truncate the
    # config it was asked to edit.
    new = text[:start] + block(insts) + text[stop:]
    open(path, "w").write(new)
    total = sum(i["count"] for i in insts)
    print(f"injected {total} child wallets from {len(insts)} spamoor instances "
          f"into {path}")


def check(path, genesis_path, insts):
    import json
    alloc = json.load(open(genesis_path))["alloc"]
    have = {a.lower(): v.get("balance", "0") for a, v in alloc.items()}
    bad = []
    checked = 0
    for inst in insts:
        # The root goes in too.  It never sends a funding transaction once the
        # children are rich, but spamoor reads its balance at startup and a
        # zero-balance root is a sign the wrong mnemonic account was used.
        for kind, addr in [("root", root_address(inst["privkey"]))] + \
                          [("child", a) for a in derive(inst)]:
            checked += 1
            bal = have.get(addr.lower())
            if bal is None or int(str(bal), 0) == 0:
                bad.append(f"{inst['name']} {kind} {addr}: "
                           f"{'absent' if bal is None else 'zero balance'}")
    if bad:
        print(f"FAIL: {len(bad)} spamoor wallets missing from {genesis_path}")
        for line in bad[:20]:
            print("  " + line)
        return 1
    print(f"OK: all {checked} spamoor wallets (roots + children) of "
          f"{len(insts)} instances are in {genesis_path} with a balance")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("sim_yaml")
    ap.add_argument("--inject", action="store_true",
                    help="rewrite the premine block in the sim config")
    ap.add_argument("--check", metavar="GENESIS_JSON",
                    help="verify the derived wallets are in a generated alloc")
    args = ap.parse_args()

    cfg = yaml.safe_load(open(args.sim_yaml))
    insts = instances(cfg)
    if not insts:
        sys.exit("no spamoor clients in the config")

    if args.check:
        sys.exit(check(args.sim_yaml, args.check, insts))
    if args.inject:
        inject(args.sim_yaml, insts)
    else:
        print(block(insts))


if __name__ == "__main__":
    main()
